spring.application.name=application-properties-reader

#### Properties to be read into the application
db.source.oracle.hostname=oracle_localhost
db.source.oracle.port=1111
db.source.oracle.user=oracle_admin
db.source.oracle.pass=oracle_pass
db.source.oracle.database=oracle_xe

db.source.postgres.hostname=postgres_localhost
db.source.postgres.port=2222
db.source.postgres.user=postgres_admin
db.source.postgres.pass=postgres_pass
db.source.postgres.database=postgres_xe